### ISSUE TITLE
Add Dark Mode to the UI

### ISSUE THREAD

**Issue by sonyccd** [sonyccd/d-star-net-list#9]
#### Description
The current UI does not support dark mode, which can improve user experience, especially for those working in low-light environments. Adding a dark mode toggle will enhance accessibility and allow users to switch between light and dark themes based on their preference.

#### Proposed Solution
1. **Dark Mode Toggle**:
   - Add a toggle button to the header or settings area to switch between light and dark mode.
   - Store the user's preference in `localStorage` so the theme persists across sessions.

2. **Dark Mode Styling**:
   - Define a set of CSS variables for colors (e.g., background, text, borders) that dynamically update based on the selected mode.
   - Use Bootstrap's built-in dark theme as a base or customize the styles to fit the application's design.

3. **Automatic Theme Detection**:
   - Detect the user's system preference (`prefers-color-scheme`) and default to that mode on initial load.
   - Allow users to override the system preference using the toggle.

4. **Responsive Design**:
   - Ensure dark mode works seamlessly across all devices and screen sizes.

#### Acceptance Criteria
- [ ] A dark mode toggle is added to the UI.
- [ ] The UI switches between light and dark mode instantly when the toggle is used.
- [ ] The user's selected mode persists across sessions using `localStorage`.
- [ ] The default mode respects the system's `prefers-color-scheme` setting.
- [ ] All UI elements, including buttons, tables, forms, and text, are styled appropriately in dark mode.

#### Implementation Details
1. **CSS Variables**:
   - Define color variables in `:root` for light mode:
     ```css
     :root {
         --bg-color: #ffffff;
         --text-color: #000000;
         --border-color: #dddddd;
     }
     ```
   - Define dark mode variables in a separate class:
     ```css
     .dark-mode {
         --bg-color: #121212;
         --text-color: #ffffff;
         --border-color: #333333;
     }
     ```
   - Use these variables throughout the CSS:
     ```css
     body {
         background-color: var(--bg-color);
         color: var(--text-color);
     }
     table {
         border-color: var(--border-color);
     }
     ```

2. **JavaScript for Theme Switching**:
   - Add a function to toggle themes:
     ```javascript
     const toggleTheme = () => {
         const body = document.body;
         body.classList.toggle("dark-mode");
         const isDarkMode = body.classList.contains("dark-mode");
         localStorage.setItem("theme", isDarkMode ? "dark" : "light");
     };

     // Load theme on page load
     document.addEventListener("DOMContentLoaded", () => {
         const savedTheme = localStorage.getItem("theme") || 
             (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
         if (savedTheme === "dark") {
             document.body.classList.add("dark-mode");
         }
     });
     ```

3. **Dark Mode Toggle Button**:
   - Add the toggle to the header:
     ```html
     <button id="themeToggle" class="btn btn-secondary">Toggle Dark Mode</button>
     ```
   - Add the event listener:
     ```javascript
     document.getElementById("themeToggle").addEventListener("click", toggleTheme);
     ```

4. **Testing**:
   - Verify the theme switch works seamlessly for all components (tables, buttons, forms, etc.).
   - Test across different browsers and devices.

#### Additional Notes
- Dark mode is increasingly common in modern applications and enhances usability for users in various lighting conditions.
- Consider extending this feature in the future to allow custom themes or colors.
